/* Version-scoped research reference. Power is a completed-level contribution,
 * never an account total or a sum of earlier levels. Relations are references,
 * not an eligibility evaluator. No cost/time/effect calculations are performed. */
(function(root){
 'use strict';
 const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 const format=(s,args)=>Object.entries(args).reduce((x,[k,v])=>x.replaceAll('{'+k+'}',String(v)),s);
 const normalized=s=>String(s||'').normalize('NFKC').toLocaleLowerCase().replace(/\s+/g,' ').trim();
 function localize(model,lang,copy){return {gameVersion:model.gameVersion,lang,copy,trees:model.trees.map(t=>({id:t.id,name:t.names[lang],hasAdditionalConditions:t.hasAdditionalConditions})),groups:model.groups.map(g=>({id:g.id,treeId:g.treeId,name:g.names[lang],search:normalized(Object.values(g.names).join(' ')+' '+g.id),icon:g.icon,levels:g.levels.map(r=>({level:r.level,totalPower:r.totalPower,conditions:{status:r.conditions.status,logic:r.conditions.logic,profile:r.conditions.profile,hasAdditionalConditions:r.conditions.hasAdditionalConditions,references:r.conditions.references.map(ref=>({kind:ref.kind,targetId:ref.targetId,level:ref.level,rank:ref.rank,name:ref.names[lang],route:ref.route}))}}))}))};}
 function index(data){const groups=new Map(data.groups.map(g=>[g.id,g])),trees=new Map(data.trees.map(t=>[t.id,t])),reverse=new Map();for(const g of data.groups)for(const row of g.levels)for(const ref of row.conditions.references){if(ref.kind!=='research')continue;const key=ref.targetId+':'+ref.level;if(!reverse.has(key))reverse.set(key,[]);const list=reverse.get(key);if(!list.some(x=>x.id===g.id&&x.level===row.level))list.push({id:g.id,name:g.name,treeId:g.treeId,level:row.level});}const counts=new Map(),labels=new Map();for(const g of data.groups){const name=g.name+' · '+trees.get(g.treeId).name;counts.set(name,(counts.get(name)||0)+1);}for(const g of data.groups){const name=g.name+' · '+trees.get(g.treeId).name;labels.set(g.id,name+(counts.get(name)>1?' · '+g.id.slice(-6):''));}return {groups,trees,reverse,labels};}
 function filterGroups(data,state){const terms=normalized(state.q).split(' ').filter(Boolean);return data.groups.filter(g=>(!state.tree||g.treeId===state.tree)&&(state.count!=='single'||g.levels.length===1)&&(state.count!=='multiple'||g.levels.length>1)&&terms.every(term=>g.search.includes(term)));}
 function stateFor(data,input={}){
  const result={q:typeof input.q==='string'?input.q:'',tree:input.tree||'',count:input.count||'all',groupId:null,level:null,invalidLink:!!input.invalidLink};
  if(result.tree&&!data.trees.some(t=>t.id===result.tree)){result.tree='';result.invalidLink=true;}
  if(!['all','single','multiple'].includes(result.count)){result.count='all';result.invalidLink=true;}
  const matches=filterGroups(data,result);let group=matches.find(g=>g.id===input.groupId);
  if(input.groupId&&!data.groups.some(g=>g.id===input.groupId))result.invalidLink=true;
  if(!group)group=matches[0];if(group){result.groupId=group.id;let level=null;if(typeof input.level==='number'&&Number.isInteger(input.level))level=input.level;else if(typeof input.level==='string'&&/^\d+$/.test(input.level))level=Number(input.level);if(input.level!=null&&!group.levels.some(r=>r.level===level))result.invalidLink=true;result.level=group.levels.find(r=>r.level===level)?.level??group.levels[0].level;}
  return result;
 }
 function readLocation(data,href){const url=new URL(href,'https://tilessurvive.net'),params=url.searchParams;const hash=new URLSearchParams(url.hash.replace(/^#/,''));const get=k=>params.has(k)?params.get(k):hash.get(k);return stateFor(data,{q:get('q')||'',tree:get('tree')||'',count:get('count')||'all',groupId:get('group'),level:get('level')});}
 function stateURL(state,pathname){const q=new URLSearchParams();if(state.q)q.set('q',state.q);if(state.tree)q.set('tree',state.tree);if(state.count&&state.count!=='all')q.set('count',state.count);if(state.groupId)q.set('group',state.groupId);if(state.level!=null)q.set('level',String(state.level));return pathname+(q.size?'?'+q.toString():'');}
 function researchURL(data,id,level){return stateURL({groupId:id,level},'/'+data.lang+'/database/research/')+'#research-detail';}
 const fmt=(data,n)=>n.toLocaleString(data.lang==='zh-tw'?'zh-TW':data.lang);
 function researchLink(data,id,level,name){return `<a href="${esc(researchURL(data,id,level))}" data-research-jump="${esc(id)}" data-level="${level}">${esc(name)}</a>`;}
 function conditionRows(data,row){const c=data.copy;return row.conditions.references.map(ref=>{const name=ref.kind==='research'?researchLink(data,ref.targetId,ref.level,ref.name):ref.route?`<a href="/${data.lang}${esc(ref.route)}">${esc(ref.name)}</a>`:esc(ref.name);return `<tr data-research-condition><td>${esc(c[ref.kind])}</td><th scope="row">${name}<small class="r60-id">${esc(ref.targetId)}</small></th><td>${ref.level}</td><td>${ref.rank===null?`<span title="${esc(c.rankUnknown)}">—</span>`:ref.rank}</td></tr>`;}).join('');}
 function detail(data,state,lookup=index(data)){
  const c=data.copy,g=lookup.groups.get(state.groupId);if(!g)return `<section class="r60-empty" data-research-empty><h2 tabindex="-1">${esc(c.empty)}</h2></section>`;
  const row=g.levels.find(r=>r.level===state.level);if(!row)throw Error('Missing explicit research level');const tree=lookup.trees.get(g.treeId),refs=row.conditions.references,reverse=lookup.reverse.get(g.id+':'+row.level)||[];
  return `<section class="r60-group" data-research-group="${esc(g.id)}"><div class="r60-group-heading">${g.icon?`<img src="${esc(g.icon.src)}" width="${g.icon.width}" height="${g.icon.height}" alt="${esc(g.name)}" loading="lazy" decoding="async">`:''}<div><p class="r60-tree">${esc(tree.name)}</p><h2 tabindex="-1" data-research-group-title>${esc(g.name)}</h2><p class="r60-id">${esc(c.identifier)}: ${esc(g.id)}</p></div></div><div class="r60-level-choice"><label for="research-level">${esc(c.level)}</label><select id="research-level" name="level" data-research-level>${g.levels.map(r=>`<option value="${r.level}"${r.level===row.level?' selected':''}>${r.level}</option>`).join('')}</select></div><div class="r60-power"><h3>${esc(c.power)}</h3><p><strong data-research-power>${fmt(data,row.totalPower)}</strong> ${esc(c.powerUnit)}</p><p class="r60-note">${esc(c.powerNote)}</p></div>${tree.hasAdditionalConditions||row.conditions.hasAdditionalConditions?`<aside class="r60-condition-notice" data-research-additional><p>${esc(c.additional)}</p><ul>${tree.hasAdditionalConditions?`<li>${esc(c.treeAdditional)}</li>`:''}${row.conditions.hasAdditionalConditions?`<li data-research-row-additional>${esc(c.rowAdditional)}</li>`:''}</ul></aside>`:''}<section class="r60-relations"><h3>${esc(c.conditions)}</h3><p class="r60-note" data-research-condition-scope>${esc(c.conditionNote)}</p>${refs.length?`<div class="r60-scroll" tabindex="0" role="region" aria-label="${esc(c.conditions)}"><table><thead><tr><th scope="col">${esc(c.kind)}</th><th scope="col">${esc(c.target)}</th><th scope="col">${esc(c.requiredLevel)}</th><th scope="col">${esc(c.rank)}</th></tr></thead><tbody>${conditionRows(data,row)}</tbody></table></div>`:`<p>${esc(c.noConditions)}</p>`}</section><section class="r60-relations"><h3>${esc(c.reverse)}</h3><p class="r60-note">${esc(c.reverseNote)}</p>${reverse.length?`<div class="r60-scroll" tabindex="0" role="region" aria-label="${esc(c.reverse)}"><table><thead><tr><th scope="col">${esc(c.research)}</th><th scope="col">${esc(c.tree)}</th><th scope="col">${esc(c.level)}</th></tr></thead><tbody>${reverse.map(ref=>`<tr data-research-reverse><th scope="row">${researchLink(data,ref.id,ref.level,ref.name)}<small class="r60-id">${esc(ref.id)}</small></th><td>${esc(lookup.trees.get(ref.treeId).name)}</td><td>${ref.level}</td></tr>`).join('')}</tbody></table></div>`:`<p>${esc(c.noReverse)}</p>`}</section><details class="r60-all-levels" open><summary>${esc(c.allLevels)}</summary><div class="r60-scroll" tabindex="0" role="region" aria-label="${esc(c.allLevels)}"><table><thead><tr><th scope="col">${esc(c.level)}</th><th scope="col">${esc(c.power)}</th></tr></thead><tbody>${g.levels.map(r=>`<tr data-research-level-row${r.level===row.level?' class="is-selected"':''}><th scope="row">${researchLink(data,g.id,r.level,String(r.level))}</th><td>${fmt(data,r.totalPower)}</td></tr>`).join('')}</tbody></table></div></details></section>`;
 }
 function mount(document,environment=root){
  const app=document.querySelector('[data-research-explorer]'),script=document.getElementById('research-phase3-data');if(!app||!script)return null;let data;try{data=JSON.parse(script.textContent);}catch(_){return null;}
  if(data.gameVersion!=='2.6.200'||!Array.isArray(data.groups)||!data.groups.length)return null;
  const lookup=index(data),form=app.querySelector('[data-research-controls]'),q=form.querySelector('[name="q"]'),tree=form.querySelector('[name="tree"]'),count=form.querySelector('[name="count"]'),group=form.querySelector('[name="group"]'),output=app.querySelector('[data-research-results]'),host=app.querySelector('[data-research-detail]'),notice=app.querySelector('[data-research-link-notice]');
  let state=readLocation(data,environment.location?.href||'/'+data.lang+'/database/research/');
  function paint(focus){const matches=filterGroups(data,state);q.value=state.q;tree.value=state.tree;count.value=state.count;group.innerHTML=matches.map(g=>`<option value="${esc(g.id)}"${g.id===state.groupId?' selected':''}>${esc(lookup.labels.get(g.id))}</option>`).join('');group.disabled=!matches.length;if(state.groupId)group.value=state.groupId;output.textContent=format(data.copy.results,{count:matches.length});notice.textContent=state.invalidLink?data.copy.invalidLink:'';notice.hidden=!state.invalidLink;host.innerHTML=detail(data,state,lookup);if(focus==='title')host.querySelector('h2')?.focus();if(focus==='level')host.querySelector('[data-research-level]')?.focus();}
  function change(next,mode='push',focus){state=stateFor(data,{...state,...next,invalidLink:false});paint(focus);const path=environment.location?.pathname||'/'+data.lang+'/database/research/';environment.history?.[mode==='replace'?'replaceState':'pushState']?.({},'',stateURL(state,path));}
  q.addEventListener('input',()=>change({q:q.value,level:null},'replace'));tree.addEventListener('change',()=>change({tree:tree.value,level:null}));count.addEventListener('change',()=>change({count:count.value,level:null}));group.addEventListener('change',()=>change({groupId:group.value,level:null}));
  form.addEventListener('submit',e=>{e.preventDefault();change({q:q.value,tree:tree.value,count:count.value,level:null});});form.addEventListener('reset',e=>{e.preventDefault();change({q:'',tree:'',count:'all',groupId:null,level:null});q.focus();});
  app.addEventListener('change',e=>{if(e.target.matches('[data-research-level]'))change({level:e.target.value},'push','level');});
  app.addEventListener('click',e=>{const a=e.target.closest('[data-research-jump]');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button>0)return;e.preventDefault();change({q:'',tree:'',count:'all',groupId:a.getAttribute('data-research-jump'),level:a.getAttribute('data-level')},'push','title');});
  const travel=()=>{state=readLocation(data,environment.location.href);paint();};environment.addEventListener?.('popstate',travel);environment.addEventListener?.('hashchange',travel);paint();form.hidden=false;app.setAttribute('data-research-ready','');return {getState:()=>({...state}),data,lookup,change};
 }
 const api={esc,format,normalized,localize,index,filterGroups,stateFor,readLocation,stateURL,researchURL,detail,mount};if(typeof module==='object'&&module.exports)module.exports=api;if(root.document)mount(root.document);
})(typeof window==='object'?window:globalThis);
