/* 2.1: source-labelled additions; never rewrite an existing game table or application. */
const fs=require('fs'),path=require('path'),{parseHTML}=require('linkedom');
const pets=require('../data/companions.json'),sea=require('../data/mariner-expansion.json');
const root=path.resolve(__dirname,'..');
const copy={
 ko:{pets:'펫 도감',sea:'바다 영웅',skills:'스킬과 효과',growth:'육성 데이터',sources:'자료와 확인 범위',related:'함께 확인할 데이터',search:'이름 검색',role:'역할',all:'전체',reset:'초기화',support:'지원',attacker:'공격',defender:'방어',details:'상세 정보',unknown:'미확인',stage:'확인된 단계',note:'공식 공지·게임 화면·커뮤니티 기록을 구분합니다. 미확인 수치는 계산에 사용하지 않습니다.',names:'펫 한국어 이름은 커뮤니티 표기를 병기했습니다. 한국어 게임 화면에서 독립적으로 확인한 공식 명칭은 아닙니다.',heroNames:'한국어 공식 명칭을 확인하지 못해 영문 게임 화면 이름을 사용합니다.',source:'출처 보기',screen:'게임 화면',community:'커뮤니티 기록',level:'레벨',attack:'공격',defense:'방어',health:'체력',power:'전투력',bonus:'영웅 보너스 비율',feed:'먹이 경험치',back:'전체 목록',missing:'전체 레벨별 비용·성급 조건·해금 시점은 아직 확보하지 못했습니다. 아래 수치는 출처 화면의 특정 단계입니다.',intro:'역할을 비교하고, 확인된 성장 자료까지 이어서 살펴보세요.',journey:'알 획득 → 부화 → 먹이·훈련 → 영웅 지원',journeyText:'정보 임무에서 알을 얻습니다. 먹이는 레벨을, 중복 펫에서 얻는 표식은 훈련을 돕습니다. 서버 진행도에 따라 이용 시점이 다릅니다.',training:'훈련 표식과 보너스',trainingNote:'0단계는 게임 화면, 1~3단계는 TilesMania의 게임 화면 판독 기록입니다. 후속 단계는 추정하지 않습니다.',marks:'단계 필요 표식',total:'누적 표식',polar:'추가 관측: 백설(북극곰)',polarText:'TilesMania의 게임 화면 기록에 등장합니다. 원본 이미지와 공식 획득 조건이 확보되지 않아 완성된 개별 도감으로 등록하지 않았습니다.',gear:'전용장비 강화표',stars:'영웅 성급표',research:'연구소',petLink:'펫 능력치 보너스',verified:'확인일',result:'결과',sourceLevel:'스킬 레벨이 명시되지 않은 커뮤니티 수치입니다. 최고 레벨 수치로 해석하지 마세요.',undineGear:'공식 v2.5.200 공지: 전용 장비 Ocean Vox의 Lv.10 효과가 개선되어 액티브 스킬 사용 시 아군 전체에 공격력 증가를 제공합니다. 공지에는 증가량이 없습니다.',gearMissing:'전용 장비의 전체 레벨별 효과·비용은 미확인입니다.',starSkill:'커뮤니티 게임 화면 판독: 별의 소원 — 전투 시작 시 전열 방어 +20%, 후열 공격 +8%, 10초. 스킬 레벨은 미확인입니다.',snapshot:'Lv.1 · 훈련 0단계 · 변신 전',petMissing:'나머지 펫의 개별 스킬·전체 성장표는 아직 검증 중입니다. 이름·역할·이미지를 확인할 수 있으며, 정보가 충분한 별뿔이만 별도 상세 페이지로 제공합니다.'},
 en:{pets:'Pet directory',sea:'Mariner heroes',skills:'Skills & effects',growth:'Growth data',sources:'Sources & coverage',related:'Continue exploring',search:'Search names',role:'Role',all:'All',reset:'Reset',support:'Support',attacker:'Attacker',defender:'Defender',details:'View details',unknown:'Unconfirmed',stage:'Observed stage',note:'Official notices, game screenshots and community records are labelled separately. Unconfirmed values are not used in calculations.',names:'Korean names follow community usage; official Korean UI names have not been independently verified.',heroNames:'The English in-game names are retained until localized official names can be verified.',source:'View source',screen:'Game screenshot',community:'Community record',level:'Level',attack:'ATK',defense:'DEF',health:'HP',power:'Power',bonus:'Hero bonus rate',feed:'Feed EXP',back:'Full directory',missing:'Full level costs, star requirements and unlock timing are not yet verified. Values below are specific observed stages.',intro:'Compare roles, then explore the available growth evidence.',journey:'Eggs → Hatching → Feeding & training → Hero bonuses',journeyText:'Intel Missions award eggs. Feed raises levels; duplicate pets supply training marks. Availability depends on State progression.',training:'Training marks & bonuses',trainingNote:'Stage 0 is visible in the screenshot; stages 1–3 follow TilesMania’s game-screen transcription. Later stages are not extrapolated.',marks:'Marks per stage',total:'Cumulative marks',polar:'Additional observation: polar bear (백설)',polarText:'Appears in TilesMania’s game-screen records. Its original image and official acquisition rules remain unverified, so no individual directory page is published.',gear:'Exclusive gear costs',stars:'Hero star data',research:'Research Lab',petLink:'Pet hero bonuses',verified:'Checked',result:'Results',sourceLevel:'The community source does not specify the skill level. This is not a verified maximum-level value.',undineGear:'Official v2.5.200: Ocean Vox Lv.10 was improved to grant an ATK boost to all allies when Undine casts her active skill. The notice does not specify the amount.',gearMissing:'Complete exclusive-gear effects and costs by level are not verified.',starSkill:'Community game-screen transcription: Star Wish grants front-row DEF +20% and back-row ATK +8% for 10 seconds at battle start. Skill level unconfirmed.',snapshot:'Lv.1 · Training 0 · Before transformation',petMissing:'Individual skills and complete growth costs remain under verification. All seven have names, roles and images; only Starhorn currently has enough evidence for a separate detail page.'},
 ja:{pets:'ペット図鑑',sea:'海の英雄',skills:'スキルと効果',growth:'育成データ',sources:'出典と確認範囲',related:'関連データ',search:'名前を検索',role:'役割',all:'すべて',reset:'リセット',support:'支援',attacker:'攻撃',defender:'防御',details:'詳細を見る',unknown:'未確認',stage:'確認済み段階',level:'レベル',attack:'攻撃',defense:'防御',health:'HP',power:'戦力',bonus:'英雄ボーナス率',feed:'餌の経験値',back:'一覧',verified:'確認日',result:'結果'},
 ru:{pets:'Каталог питомцев',sea:'Морские герои',skills:'Навыки и эффекты',growth:'Развитие',sources:'Источники и полнота данных',related:'Связанные данные',search:'Поиск по имени',role:'Роль',all:'Все',reset:'Сбросить',support:'Поддержка',attacker:'Атака',defender:'Защита',details:'Подробнее',unknown:'Не подтверждено',stage:'Проверенный этап',level:'Уровень',attack:'Атака',defense:'Защита',health:'Здоровье',power:'Мощь',bonus:'Бонус героям',feed:'Опыт корма',back:'Каталог',verified:'Проверено',result:'Результаты'},
 'zh-tw':{pets:'寵物圖鑑',sea:'海洋英雄',skills:'技能與效果',growth:'成長資料',sources:'來源與確認範圍',related:'相關資料',search:'搜尋名稱',role:'角色',all:'全部',reset:'重設',support:'支援',attacker:'攻擊',defender:'防禦',details:'查看詳情',unknown:'待確認',stage:'已確認階段',level:'等級',attack:'攻擊',defense:'防禦',health:'生命',power:'戰力',bonus:'英雄加成率',feed:'飼料經驗',back:'完整列表',verified:'確認日期',result:'結果'}
};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function read(route){return parseHTML(fs.readFileSync(path.join(root,route,'index.html'),'utf8')).document;}
function write(route,d){fs.mkdirSync(path.join(root,route),{recursive:true});fs.writeFileSync(path.join(root,route,'index.html'),'<!DOCTYPE html>\n'+d.documentElement.outerHTML+'\n');}
function node(d,s){const t=d.createElement('template');t.innerHTML=s;return t.content;}
function section(d,id,html,before){d.getElementById(id)?.remove();const n=node(d,`<section class="ts-expansion" id="${id}">${html}</section>`);if(before)before.before(n);else d.querySelector('main').append(n);}
function newPage(route,lang,title,description,body,img){return parseHTML(`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | TilesSurvive.net</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://tilessurvive.net/${route}/"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="https://tilessurvive.net/${route}/"><meta property="og:image" content="https://tilessurvive.net${img}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:title,url:'https://tilessurvive.net/'+route+'/',inLanguage:lang,dateModified:'2026-10-09'})}</script></head><body><main class="container page-main" id="main">${body}</main></body></html>`).document;}
for(const lang of Object.keys(copy)){
 const t={...copy.en,...copy[lang],...(require('../data/expansion-copy.json')[lang]||{})},ko=lang==='ko',p=`/${lang}/`,title=pet=>ko?pet.ko:pet.name;
 const links=`<nav class="ts-context-links" aria-label="${t.related}"><a href="${p}database/hero-star/">${t.stars}</a><a href="${p}database/exclusive-gear/">${t.gear}</a><a href="${p}buildings/lab/">${t.research}</a><a href="${p}database/pet-system/">${t.petLink}</a></nav>`;
 const petRoute=lang+'/database/pet-system',d=read(petRoute);
 d.documentElement.setAttribute('data-content','pets');
 d.querySelector('h1').textContent=t.pets;
 d.querySelector('title').textContent=t.pets+' · 7 | TilesSurvive.net';
 d.querySelector('meta[name=description]').setAttribute('content',t.intro+' '+t.journey);
 d.querySelector('.hero-card .eyebrow')?.remove();
 section(d,'pet-directory',`<div class="ts-section-heading"><h2>${t.pets}</h2><p>${t.verified} 2026-10-09 · 7</p></div><form class="ts-controls" data-pet-controls><label>${t.search}<input type="search" name="q" autocomplete="off"></label><label>${t.role}<select name="role"><option value="">${t.all}</option>${['Support','Attacker','Defender'].map(r=>`<option value="${r}">${t[r.toLowerCase()]}</option>`).join('')}</select></label><button type="reset">${t.reset}</button><output aria-live="polite" data-pet-count>7 / 7</output></form><div class="ts-pet-list">${pets.pets.map(pet=>`<article class="ts-pet-row" data-pet-role="${pet.role}" data-pet-name="${esc(pet.name+' '+pet.ko+' '+(pet.alias||''))}" id="pet-${pet.id}"><img src="/img/pets/${pet.id}.webp" alt="${title(pet)}" width="72" height="72" loading="lazy"><div><h3>${title(pet)}</h3><p>${ko?pet.name+' · '+pet.animalKo:pet.animal}${pet.alias?' · '+pet.alias:''}</p></div><span>${t[pet.role.toLowerCase()]}</span>${pet.detail?`<a href="${p}database/pet-system/starhorn/">${t.details} →</a>`:pet.skill?`<details><summary>${t.skills}</summary><p>${ko?pet.skillKo:pet.skill}</p></details>`:`<span class="ts-evidence-label">${t.skills} · ${t.unknown}</span>`}</article>`).join('')}</div><p>${t.petMissing}</p><p class="ts-evidence-label">${t.names}</p><div class="ts-source-line"><a href="${pets.sources.announcement}">Tiles Survive · ${t.source}</a><a href="${pets.sources.announcementMirror}">Archive</a><a href="${pets.sources.images}">${t.screen} · LDShop</a></div>`,d.querySelector('main .home-section'));
 section(d,'pet-growth',`<h2>${t.growth}</h2><div class="ts-editorial-grid"><div><h3>${t.journey}</h3><p>${t.journeyText}</p><h3>${t.training}</h3><p>${t.trainingNote}</p><div class="ts-table-wrap" tabindex="0" role="region" aria-label="${t.training}"><table data-static><thead><tr><th>${t.stage}</th><th>${t.bonus}</th><th>${t.marks}</th><th>${t.total}</th></tr></thead><tbody>${pets.trainingObserved.map((s,i)=>`<tr><td>${s.stage}</td><td>${s.bonusRate}%</td><td>${s.marks}</td><td>${pets.trainingObserved.slice(0,i+1).reduce((a,b)=>a+b.marks,0)}</td></tr>`).join('')}</tbody></table></div><p><a href="${pets.sources.community}">TilesMania · ${t.community}</a></p><h3>${t.polar}</h3><p>${t.polarText}</p></div><figure class="ts-evidence-figure"><img src="/img/pets/official-lineup.jpg" alt="Tiles Survive pet announcement" width="1080" height="1080" loading="lazy"><figcaption>Tiles Survive · ${t.source}</figcaption></figure></div>`);
 for(const m of d.querySelectorAll('meta[property="og:title"]'))m.setAttribute('content',t.pets);
 for(const m of d.querySelectorAll('meta[property="og:description"]'))m.setAttribute('content',t.intro+' '+t.journey);
 write(petRoute,d);
 const star=pets.pets.find(p=>p.id==='starhorn'),starRoute=petRoute+'/starhorn';
 const starBody=`<nav class="breadcrumb"><a href="${p}database/pet-system/">${t.pets}</a> / ${title(star)}</nav><section class="ts-character-intro"><div><p class="ts-overline">${t.pets} / SSR / ${t.defender}</p><h1>${title(star)}</h1><p>${star.name} · ${ko?star.animalKo:star.animal}</p><p>${t.snapshot}</p><nav class="ts-context-links"><a href="${p}database/pet-system/">← ${t.back}</a><a href="${p}heroes/">${t.petLink}</a></nav></div><img src="/img/pets/growth-source.webp" alt="Starhorn Lv.1 game screenshot" width="731" height="920" loading="eager"></section><section class="ts-expansion"><h2>${t.growth}</h2><p>${t.screen} · ${t.snapshot}</p><dl class="ts-data-strip">${[['attack',157],['defense',31],['health','10.31K'],['power','40,819'],['bonus','25%']].map(([key,value])=>`<div><dt>${t[key]}</dt><dd>${value}</dd></div>`).join('')}</dl><h3>${t.feed}</h3><p>+50 / +100 / +200 / +500 EXP · Lv.1 → 2: 120 EXP</p><h2>${t.skills}</h2><p>${t.starSkill}</p><h2>${t.sources}</h2><p>${t.note}</p><p>${t.missing}</p><div class="ts-source-line"><a href="${pets.sources.images}">${t.screen} · LDShop</a><a href="${pets.sources.community}">${t.community} · TilesMania</a><a href="${pets.sources.official}">v2.6.100</a></div></section>${links}`;
 write(starRoute,newPage(starRoute,lang,title(star),t.snapshot+' · '+t.growth,starBody,'/img/pets/growth-source.webp'));
 for(const h of sea.heroes){
  const route=lang+'/heroes/'+h.id;
  const body=`<nav class="breadcrumb"><a href="${p}heroes/">${t.sea}</a> / ${h.name}</nav><section class="ts-character-intro"><div><p class="ts-overline">${t.sea} / SSR / ${ko?h.roleKo:h.role}</p><h1>${h.name}</h1><p>${t.skillText?.[h.id]?.[1]||(ko?h.skills[1].ko:h.skills[1].en)}</p><p class="ts-evidence-label">${t.heroNames}</p><nav class="ts-context-links">${['shark','lagnar','undine','knotty'].filter(id=>id!==h.id).map(id=>`<a href="${p}heroes/${id}/">${id==='lagnar'?(ko?'라그나':'Ragnar'):id==='shark'?(ko?'샤크':'Shark'):id==='undine'?'Undine':'Knotty'}</a>`).join('')}</nav></div><img src="${h.image}" alt="${h.name} game screenshot" loading="eager"></section><section class="ts-expansion"><h2>${t.skills}</h2><p>${t.note}</p><div class="ts-skill-list">${h.skills.map((s,i)=>`<details class="ts-skill" ${i===1?'open':''}><summary><span>${s.name}</span></summary><div class="ts-skill-body"><p>${t.skillText?.[h.id]?.[i]||(ko?s.ko:s.en)}</p>${s.stages?`<div data-stage-picker><label>${t.stage}<select>${s.stages.map((x,j)=>`<option value="${j}">Lv.${x.level}</option>`).join('')}</select></label>${s.stages.map((x,j)=>`<p data-stage-result="${j}"><strong>Lv.${x.level} · ${x.value}${s.unit}</strong></p>`).join('')}</div>`:''}<p class="ts-evidence-label">${s.evidence==='game-screen'?t.screen:t.sourceLevel}</p></div></details>`).join('')}</div><details class="ts-source-details"><summary>${t.screen} · ${t.source}</summary><img src="${h.skillImage}" alt="${h.name} skill level evidence" loading="lazy"></details></section><section class="ts-expansion"><h2>${t.growth}</h2><p>${t.missing}</p>${links}<h3>${t.gear}</h3><p>${h.id==='undine'?t.undineGear:t.gearMissing}</p></section><section class="ts-expansion"><h2>${t.sources}</h2><p>${t.verified}: 2026-10-09</p><div class="ts-source-line"><a href="${h.guide}">Tiles Survive Guide</a><a href="${sea.imageSource}">${t.screen} · LDShop</a>${h.official?`<a href="${h.official}">v2.5.200</a>`:''}</div></section>`;
  write(route,newPage(route,lang,h.name,t.sea+' · SSR · '+h.role+' · '+t.skills,body,h.image));
 }
 for(const id of ['shark','lagnar']){const route=lang+'/heroes/'+id,hd=read(route);section(hd,'mariner-connections',`<h2>${t.sea}</h2><nav class="ts-context-links">${['shark','lagnar','undine','knotty'].filter(x=>x!==id).map(x=>`<a href="${p}heroes/${x}/">${x==='lagnar'?(ko?'라그나':'Ragnar'):x==='shark'?(ko?'샤크':'Shark'):x==='undine'?'Undine':'Knotty'}</a>`).join('')}</nav><p>${t.missing}</p>${links}`);write(route,hd);}
 const list=read(lang+'/heroes');list.querySelectorAll('[data-added-hero]').forEach(n=>n.remove());
 for(const nested of [...list.querySelectorAll('.hero-item .hero-item')]){
   const grid=nested.closest('.hero-grid');if(grid)grid.append(nested);
 }
 const group=list.querySelector('#heroes-sea .hero-grid')||list.querySelector('.hero-item[href*="shark"]')?.parentElement;
 if(!group)throw Error('Sea hero group missing '+lang);
 for(const h of sea.heroes)group.append(node(list,`<a class="hero-item" data-added-hero href="${p}heroes/${h.id}/"><span class="hero-thumb"><img src="${h.image}" alt="${h.name}" loading="lazy"></span><div class="hero-body"><h3>${h.name}</h3><p>${ko?h.roleKo:h.role}</p><div class="hero-meta-row"><span class="chip chip-sea">${ko?'바다':lang==='en'?'Sea':lang==='ja'?'海':lang==='ru'?'Море':'海洋'}</span><span class="chip">SSR</span></div></div></a>`));
 // Update count labels only; preserve hero copy and all existing entries.
 for(const n of list.querySelectorAll('.chip-sea'))if(/2/.test(n.textContent))n.textContent=n.textContent.replace('2','4');
 const seaCount=list.querySelector('#heroes-sea .faction-count');if(seaCount)seaCount.textContent=seaCount.textContent.replace('2','4');
 write(lang+'/heroes',list);
 const listFile=path.join(root,lang,'heroes','index.html');fs.writeFileSync(listFile,fs.readFileSync(listFile,'utf8').replace(/^[ \t]+$/gm,''));
 const home=read(lang);section(home,'discovery-21',`<div class="ts-section-heading"><h2>${t.sea} & ${t.pets}</h2><p>${t.intro}</p></div><div class="ts-discovery"><a href="${p}heroes/undine/"><img src="/img/heroes/undine-game.webp" alt="Undine" loading="lazy"><span><strong>Undine & Knotty</strong><small>${t.skills} →</small></span></a><a href="${p}database/pet-system/"><img src="/img/pets/official-lineup.jpg" alt="" loading="lazy"><span><strong>${t.pets}</strong><small>${t.growth} →</small></span></a></div>`,home.querySelector('main .home-section'));write(lang,home);
}
console.log('2.1 content: 7 pet entries, 2 sea heroes and Starhorn detail in 5 languages');

